version: '3'

services:
  web:
    build:
      context: ./keygen
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis:5
    ports:
     - "6379:6379"
