# Generated by Django 3.1.5 on 2021-01-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=255, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Сгенерированный ключ',
                'verbose_name_plural': 'Сгенерированные ключи',
            },
        ),
    ]
