# Generated by Django 3.1.5 on 2021-01-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20210127_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedkey',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
